language: node_js
node_js:
  - 13
#name: GitHub Action for Ember Testing
#uses: alexlafroscia/actions-ember-testing@v1.0.0

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple_node_travic_ci2 .
  - docker tag simple_node_travic_ci2 toyintheisaac/simple_node_travic_ci:latest
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push toyintheisaac/simple_node_travic_ci